if has("gui_running")
"    set background=light
"    colorscheme solarized
"    colorscheme OceanicNext
    set guioptions-=T
    set guioptions-=l
    set guioptions-=L
    set guioptions-=r
    set guioptions-=R
endif

if has("win32")
    set guifont=Consolas:h11:cANSI
    map <C-V> "+gP
    map <C-C> "+y
endif

let g:airline_theme='oceanicnext'

set number
"set relativenumber
set ts=4 sw=4 et

command WQ wq
command Wq wq
command W w
command Q q

imap jj <Esc>

set exrc
"set secure
