runtime! archlinux.vim

call plug#begin('~/.vim/plugged')
  Plug 'tpope/vim-sensible'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-repeat'
call plug#end()

set relativenumber
set number

set ts=2 sw=2 et

imap jj <Esc>
